package com.masters_of_destiny.Ai.People.OccupationStuff;

public enum OccupationTypes {
    FOODSERVICE, // SERVERS, BARTENDERS, COOKS
    FARMING, // IF IT PRODUCES FOOD, IT'S HERE
    CONSTRUCTION, //  IF IT MAKES A BUILDING, IT'S HERE
    GUARDING, // LIKE POLICE BUT FOR SPECIFIC THING/PERSON
    EMERGENCYRESPONSE, // POLICE, FIRE, MEDICAL
    GOVERNANCE, // ANY KIND OF POLITICIAN OR NOBLE
    MANAGEMENT, // OVERSEER, MANAGER, OWNER, DIRECTOR
    TRANSPORTATION, // BOATS, CARRIAGES, TRAINS, HORSEBACK, ANYTHING TO MOVE PEOPLE OR OBJECTS
    MINING, // DIGGING MATERIALS OUT OF THE GROUND
    CRAFTING, // SMELTING, WHITTLING, PUTTING-TOGETHER, TOY-MAKER, ALCHEMIST CREATION OF NON-BUILDINGS
    SERVANT, // SLAVES, BUTLERS, SERVANTS, ASSISTANTS
    MONEY, // BANKERS, ACCOUNTANTS, ETC
    INSTRUCTION, // TEACHERS, COACHES, MENTORS
    MEDICAL, // A REGULAR DOCTOR
    ENTERTAINMENT, // ACTOR, SINGER, DANCER, BARD
    LITERARY, // LIBRARIAN, SCHOLAR, SCRIBE, HISTORIAN, TRANSLATOR, DOESN'T TEACH BUT WORKS WITH KNOWLEDGE
    RESOURCEGATHERING, // HUNTER, GATHERER, WOODCUTTER, ETC
}
