package com.masters_of_destiny.DataObjects.Spells;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class StandardSpells {
    //use the list here https://www.dndbeyond.com/spells?sort=level some you can't see details for but if you google that specific spell you'll find its details
    //TODO: fill out all 9 spell tiers. Doesn't need to be 100% of the spells (some are too much to give to an NPC

    //Cantrips (level 0)
    //public static final Spell spell = new Spell("", 0, "", "", 0, "", "", "", "");
    public static final Spell acidSplash = new Spell("Acid Splash",0,"","1 action",60,"v,s","instant","sorc, wiz","You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.");
    public static final Spell bladeWard = new Spell("Blade Ward", 0, "", "1 action", 0, "", "1 round", "", "You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.");
    public static final Spell boomingBlade = new Spell("Booming Blade", 0, "", "1 action", 5, "v,m (a weapon)", "1 round", "", "As part of the action used to cast this spell, you must make a melee attack with a weapon against one creature within the spell's range, otherwise the spell fails. On a hit, the target suffers the attack's normal effects, and it becomes sheathed in booming energy until the start of your next turn. If the target willingly moves be- fore then, it immediately takes 1d8 thunder damage, and the spell ends. At 5th level, the melee attack deals an extra 1d8 thunder damage to the target, and the damage the target takes for moving increases to 2d8. Both damage rolls increase by 1d8 at 11th level and 17th level.");
    public static final Spell chillTouch = new Spell("Chill Touch", 0, "", "1 action", 120, "", "1 round", "sorc, wiz, war", "You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged spell attack against the creature to assail it with the chill of the grave. On a hit, the target takes 1d8 necrotic damage, and it can’t regain hit points until the start of your next turn. Until then, the hand clings to the target. If you hit an undead target, it also has disadvantage on attack rolls against you until the end of your next turn.");
    public static final Spell controlFlames = new Spell("Control Flames", 0, "", "1 action", 60, "s", "instant", "", "You choose nonmagical flame that you can see within range and that fits within a 5-foot cube. You affect it in one of the following ways: 1, You instantaneously expand the flame 5 feet in one direction, provided that wood or other fuel is present in the new location. 2, You instantaneously extinguish the flames within the cube. 3, You double or halve the area of bright light and dim light cast by the flame, change its color, or both. The change lasts for 1 hour. 4, You cause simple shapes—such as the vague form of a creature, an inanimate object, or a location—to appear within the flames and animate as you like. The shapes last for 1 hour. If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.");
    public static final Spell createBonfire = new Spell("Create Bonfire", 0, "", "1 action", 60, "v,s", "1 minute", "", "You create a bonfire on ground that you can see within range. Until the spell ends, the magic bonfire fills a 5-foot cube. Any creature in the bonfire’s space when you cast the spell must succeed on a Dexterity saving throw or take 1d8 fire damage. A creature must also make the saving throw when it moves into the bonfire’s space for the first time on a turn or ends its turn there. The bonfire ignites flammable objects in its area that aren’t being worn or carried. The spell’s damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).");
    public static final Spell dancingLights = new Spell("Dancing Lights", 0, "", "1 action", 120, "v,s,m", "concentration, up to 1 min", "", "You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration. You can also combine the four lights into one glowing vaguely humanoid form of Medium size. Whichever form you choose, each light sheds dim light in a 10-foot radius. As a bonus action on your turn, you can move the lights up to 60 feet to a new spot within range. A light must be within 20 feet of another light created by this spell, and a light winks out if it exceeds the spell’s range");
    public static final Spell druidcraft = new Spell("Druidcraft", 0, "", "1 action", 30, "v,s", "instant", "", "Whispering to the spirits of nature, you create one of the following effects within range: You create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24 hours. The effect might manifest as a golden orb for clear skies, a cloud for rain, falling snowflakes for snow, and so on. This effect persists for 1 round. You instantly make a flower blossom, a seed pod open, or a leaf bud bloom. You create an instantaneous, harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small animal, or the faint odor of skunk. The effect must fit in a 5-foot cube. You instantly light or snuff out a candle, a torch, or a small campfire.");
    public static final Spell eldritchBlast = new Spell("Eldritch Blast", 0, "", "1 action", 120, "v,s", "instant", "", "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.");
    public static final Spell encodeThoughts = new Spell("Encode Thoughts", 0, "", "1 action", 0, "s", "8 hours", "", "You pull a memory, an idea, or a message from your mind and transform it into a tangible string of glowing energy called a thought strand, which persists for the duration or until you cast this spell again. The thought strand appears in an unoccupied space within 5 feet of you as a Tiny, weightless, semisolid object that can be held and carried like a ribbon. It is otherwise stationary. If you cast this spell while concentrating on a spell or an ability that allows you to read or manipulate the thoughts of others (such as Detect Thoughts or Modify Memory), you can transform the thoughts or memories you read, rather than your own, into a thought strand. Casting this spell while holding a thought strand allows you to instantly receive whatever memory, idea, or message the thought strand contains. (Casting Detect Thoughts on the strand has the same effect.)");
    public static final Spell fireBolt = new Spell("Fire Bolt", 0, "", "1 action", 0, "v,s", "instant", "", "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn’t being worn or carried.");
    public static final Spell friends = new Spell("Friends", 0, "", "1 action", 0, "S, M (a small amount of makeup applied to the face as this spell is cast)", "Concentration up to 1 min", "", "For the duration, you have advantage on all Charisma checks directed at one creature of your choice that isn’t hostile toward you. When the spell ends, the creature realizes that you used magic to influence its mood and becomes hostile toward you. A creature prone to violence might attack you. Another creature might seek retribution in other ways (at the DM’s discretion), depending on the nature of your interaction with it.");
    public static final Spell frostbite = new Spell("Frostbite", 0, "", "1 action", 60, "v,s", "instant", "", "You cause numbing frost to form on one creature that you can see within range. The target must make a Constitution saving throw. On a failed save, the target takes 1d6 cold damage, and it has disadvantage on the next weapon attack roll it makes before the end of its next turn. The spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).");
    public static final Spell greenFlameBlade = new Spell("Green-Flame Blade", 0, "", "1 action", 5, "V, M (a weapon)", "instant", "", "As part of the action used to cast this spell, you must make a melee attack with a weapon against one creature within the spell's range, otherwise the spell fails. On a hit, the target suffers the attack's normal effects, and green fire leaps from the target to a different creature of your choice that you can see within 5 feet of it. The second creature takes fire damage equal to your spellcasting ability modifier. This spell's damage increases when you reach higher levels. At 5th level, the melee attack deals an extra 1d8 fire damage to the target, and the fire damage to the second creature increases to 1d8 + your spellcasting ability modifier. Both damage rolls increase by 1d8 at 11th level and 17th level.");
    public static final Spell guidance = new Spell("Guidance", 0, "", "1 action", 0, "v,s", "conc, 1 min", "", "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.");
    public static final Spell gust = new Spell("Gust", 0, "", "1 action", 30, "v,s", "instant", "", "You seize the air and compel it to create one of the following effects at a point you can see within range: 1, One Medium or smaller creature that you choose must succeed on a Strength saving throw or be pushed up to 5 feet away from you. 2, You create a small blast of air capable of moving one object that is neither held nor carried and that weighs no more than 5 pounds. The object is pushed up to 10 feet away from you. It isn’t pushed with enough force to cause damage. 3, You create a harmless sensory effect using air, such as causing leaves to rustle, wind to slam shutters shut, or your clothing to ripple in a breeze.");
    public static final Spell infestation = new Spell("Infestation", 0, "", "1 action", 30, "v,s,m", "instant", "", "You cause a cloud of mites, fleas, and other parasites to appear momentarily on one creature you can see within range. The target must succeed on a Constitution saving throw, or it takes 1d6 poison damage and moves 5 feet in a random direction if it can move and its speed is at least 5 feet. Roll a d4 for the direction: 1., north; 2, south; 3, east; or 4, west. This movement doesn’t provoke opportunity attacks, and if the direction rolled is blocked, the target doesn't move. The spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).");
    public static final Spell light = new Spell("Light", 0, "", "1 action", 0, "v,m: firefly or phosphorescent moss", "1 hr", "", "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light. The spell ends if you cast it again or dismiss it as an action. If you target an object held or worn by a hostile creature, that creature must succeed on a Dexterity saving throw to avoid the spell.");
    public static final Spell lightningLure = new Spell("Lightning Lure", 0, "", "1 Action", 15, "v", "instant", "", "You create a lash of lightning energy that strikes at one creature of your choice that you can see within range. The target must succeed on a Strength saving throw or be pulled up to 10 feet in a straight line toward you and then take 1d8 lightning damage if it is within 5 feet of you. This spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).");
    public static final Spell mageHand = new Spell("Mage Hand", 0, "", "1 action", 30, "v,s", "1 min", "", "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again. You can use your action to control the hand. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it. The hand can’t attack, activate magic items, or carry more than 10 pounds.");
    public static final Spell magicStone = new Spell("Magic Stone", 0, "", "1 bonus action", 0, "v,s", "1 min", "", "You touch one to three pebbles and imbue them with magic. You or someone else can make a ranged spell attack with one of the pebbles by throwing it or hurling it with a sling. If thrown, it has a range of 60 feet. If someone else attacks with the pebble, that attacker adds your spellcasting ability modifier, not the attacker’s, to the attack roll. On a hit, the target takes bludgeoning damage equal to 1d6 + your spellcasting ability modifier. Hit or miss, the spell then ends on the stone. If you cast this spell again, the spell ends early on any pebbles still affected by it.");
    public static final Spell mending = new Spell("Mending", 0, "", "1 minute (6 turns)", 0, "v,s,m", "instant", "", "This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage. This spell can physically repair a magic item or construct, but the spell can’t restore magic to such an object.");
    public static final Spell message = new Spell("Message", 0, "", "1 action", 120, "v,s,m", "1 round", "", "You point your finger toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear. You can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier. Magical silence, 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood blocks the spell. The spell doesn’t have to follow a straight line and can travel freely around corners or through openings.");
    public static final Spell mindSliver = new Spell("Mind Sliver", 0, "", "1 action", 60, "v", "1 round", "", "You drive a disorienting spike of psychic energy into the mind of one creature you can see within range. The target must make an Intelligence saving throw. Unless the saving throw is successful, the target takes 1d6 psychic damage, and the first time it makes a saving throw before the end of your next turn, it must roll a d4 and subtract the number rolled from the save. This spell’s damage increases by 1d6 when you reach certain levels: 5th level (2d6), 11th level (3d6), and 17th level (4d6).");
    public static final Spell minorIllusion = new Spell("Minor Illusion", 0, "", "1 action", 30, "s,m (a bit of fleece)", "1 min", "", "You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again. If you create a sound, its volume can range from a whisper to a scream. It can be your voice, someone else’s voice, a lion’s roar, a beating of drums, or any other sound you choose. The sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends. If you create an image of an object—such as a chair, muddy footprints, or a small chest—it must be no larger than a 5-foot cube. The image can’t create sound, light, smell, or any other sensory effect. Physical interaction with the image reveals it to be an illusion, because things can pass through it. If a creature uses its action to examine the sound or image, the creature can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the illusion becomes faint to the creature.");
    public static final Spell moldEarth = new Spell("Mold Earth", 0, "", "1 action", 30, "s", "instant", "", "You choose a portion of dirt or stone that you can see within range and that fits within a 5-foot cube. You manipulate it in one of the following ways: 1, If you target an area of loose earth, you can instantaneously excavate it, move it along the ground, and deposit it up to 5 feet away. This movement doesn’t have enough force to cause damage. 2, You cause shapes, colors, or both to appear on the dirt or stone, spelling out words, creating images, or shaping patterns. The changes last for 1 hour. 3, If the dirt or stone you target is on the ground, you cause it to become difficult terrain. Alternatively, you can cause the ground to become normal terrain if it is already difficult terrain. This change lasts for 1 hour. If you cast this spell multiple times, you can have no more than two of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.");
    public static final Spell poisonSpray = new Spell("Poison Spray", 0, "", "1 action", 10, "v,s", "instant", "", "You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage.");
    public static final Spell prestidigitation = new Spell("Prestidigitation", 0, "", "1 action", 10, "v,s", "up to 1 hr", "", "This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range: 1, You create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor. 2, You instantaneously light or snuff out a candle, a torch, or a small campfire. 3, You instantaneously clean or soil an object no larger than 1 cubic foot. 4, You chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour. 5, You make a color, a small mark, or a symbol appear on an object or a surface for 1 hour. 6, You create a nonmagical trinket or an illusory image that can fit in your hand and that lasts until the end of your next turn. If you cast this spell multiple times, you can have up to three of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.");
    public static final Spell primalSavagery = new Spell("Primal Savagery", 0, "", "1 action", 0, "s", "instant", "", "You channel primal magic to cause your teeth or fingernails to sharpen, ready to deliver a corrosive attack. Make a melee spell attack against one creature within 5 feet of you. On a hit, the target takes 1d10 acid damage. After you make the attack, your teeth or fingernails return to normal. The spell’s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).");
    public static final Spell produceFlame = new Spell("Produce Flame", 0, "", "1 action", 0, "v,s", "10 min", "", "A flickering flame appears in your hand. The flame remains there for the duration and harms neither you nor your equipment. The flame sheds bright light in a 10-foot radius and dim light for an additional 10 feet. The spell ends if you dismiss it as an action or if you cast it again. You can also attack with the flame, although doing so ends the spell. When you cast this spell, or as an action on a later turn, you can hurl the flame at a creature within 30 feet of you. Make a ranged spell attack. On a hit, the target takes 1d8 fire damage.");
    public static final Spell rayOfFrost = new Spell("Ray of Frost", 0, "", "1 action", 60, "v,s", "instant", "", "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.");
    public static final Spell resistance = new Spell("Resistance", 0, "", "1 action", 0, "v,s,m (a miniature cloak)", "Concentration, up to 1 min", "", "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice. It can roll the die before or after making the saving throw. The spell then ends.");
    public static final Spell sacredFlame = new Spell("Sacred Flame", 0, "", "1 action", 60, "v,s", "instant", "", "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.");
    public static final Spell shapeWater = new Spell("Shape Water", 0, "", "1 action", 30, "s", "", "", "You choose an area of water that you can see within range and that fits within a 5-foot cube. You manipulate it in one of the following ways: 1, You instantaneously move or otherwise change the flow of the water as you direct, up to 5 feet in any direction. This movement doesn’t have enough force to cause damage. 2, You cause the water to form into simple shapes and animate at your direction. This change lasts for 1 hour. 3, You change the water’s color or opacity. The water must be changed in the same way throughout. This change lasts for 1 hour. 4, You freeze the water, provided that there are no creatures in it. The water unfreezes in 1 hour. If you cast this spell multiple times, you can have no more than two of its non-instantaneous effects active at a time, and you can dismiss such an effect as an action.");
    public static final Spell shillelagh = new Spell("Shillelagh", 0, "", "1 bonus action", 0, "v,s,m (Mistletoe, a shamrock leaf, and a club or quarterstaff)", "1 min", "", "The wood of a club or quarterstaff you are holding is imbued with nature’s power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon’s damage die becomes a d8. The weapon also becomes magical, if it isn’t already. The spell ends if you cast it again or if you let go of the weapon.");
    public static final Spell shockingGrasp = new Spell("Shocking Grasp", 0, "", "1 action", 0, "v,s", "instant", "", "Lightning springs from your hand to deliver a shock to a creature you try to touch. Make a melee spell attack against the target. You have advantage on the attack roll if the target is wearing armor made of metal. On a hit, the target takes 1d8 lightning damage, and it can’t take reactions until the start of its next turn.");
    public static final Spell spareTheDying = new Spell("Spare The Dying", 0, "", "1 action", 0, "v,s", "instant", "", "You touch a living creature that has 0 hit points. The creature becomes stable. This spell has no effect on undead or constructs.");
    public static final Spell thaumaturgy = new Spell("Thaumaturgy", 0, "", "", 30, "v", "up to 1 min", "", "You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range: Your voice booms up to three times as loud as normal for 1 minute. You cause flames to flicker, brighten, dim, or change color for 1 minute. You cause harmless tremors in the ground for 1 minute. You create an instantaneous sound that originates from a point of your choice within range, such as a rumble of thunder, the cry of a raven, or ominous whispers. You instantaneously cause an unlocked door or window to fly open or slam shut. You alter the appearance of your eyes for 1 minute. If you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as an action.");
    public static final Spell thornWhip = new Spell("Thorn Whip", 0, "", "1 action", 20, "v,s,m (the stem of a thorned plant)", "instant", "", "You create a long, vine-like whip covered in thorns that lashes out at your command toward a creature in range. Make a melee spell attack against the target. If the attack hits, the creature takes 1d6 piercing damage, and if the creature is Large or smaller, you pull the creature up to 10 feet closer to you. This spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).");
    public static final Spell thunderclap = new Spell("Thunderclap", 0, "", "1 action", 5, "s", "instant", "", "You create a burst of thunderous sound that can be heard up to 100 feet away. Each creature within range, other than you, must succeed on a Constitution saving throw or take 1d6 thunder damage.");
    public static final Spell tollTheDead = new Spell("Toll the Dead", 0, "", "1 action", 60, "v,s", "instant", "", "You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take 1d8 necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage. The spell’s damage increases by one die when you reach 5th level (2d8 or 2d12), 11th level (3d8 or 3d12), and 17th level (4d8 or 4d12).");
    public static final Spell trueStrike = new Spell("True Strike", 0, "", "1 action", 30, "s", "concentration up to 1 round", "", "You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target’s defenses. On your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn’t ended.");
    public static final Spell viciousMockery = new Spell("Vicious Mockery", 0, "", "1 action", 60, "v", "instant", "", "You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you (though it need not understand you), it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.");
    public static final Spell wordOfRadiance = new Spell("Word of Radiance", 0, "", "1 action", 0, "v,m (a holy symbol)", "instant", "", "You utter a divine word, and burning radiance erupts from you. Each creature of your choice that you can see within range must succeed on a Constitution saving throw or take 1d6 radiant damage.");

    //Level 1
    //public static final Spell spell = new Spell("", 1, "", "1 action", 0, "", "", "", "");
    public static final Spell alarm = new Spell("Alarm", 1, "", "1 minute", 30, "v,s,m (a tiny bell and a piece of fine silver wire)", "instant", "", "You set an alarm against unwanted intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a Tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is mental or audible. A mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping. An audible alarm produces the sound of a hand bell for 10 seconds within 60 feet");
    public static final Spell absorbElements = new Spell("Absorb Elements", 1, "", "1 reaction", 0, "s", "1 round", "", "The spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type, and the spell ends.  When you cast this spell using a spell slot of 2nd level or higher, the extra damage increases by 1d6 for each slot level above 1st.");
    public static final Spell animalFriendship = new Spell("Animal Friendship", 1, "", "1 action", 30, "v,s,m (a morsel of food)", "24 hours", "", "This spell lets you convince a beast that you mean it no harm. Choose a beast that you can see within range. It must see and hear you. If the beast's Intelligence is 4 or higher, the spell fails. Otherwise, the beast must succeed on a Wisdom saving throw or be charmed by you for the spell's duration. If you or one of your companions harms the target, the spell ends. When you cast this spell using a spell slot of 2nd level or higher, you can affect one additional beast for each slot level above 1st.");
    public static final Spell arcaneWeapon = new Spell("Arcane Weapon", 1, "", "1 bonus action", 0, "v,s", "1 hour", "", "You channel arcane energy into one simple or martial weapon you’re holding, and choose one damage type: acid, cold, fire, lightning, poison, or thunder. Until the spell ends, you deal an extra 1d6 damage of the chosen type to any target you hit with the weapon. If the weapon isn’t magical, it becomes a magic weapon for the spell’s duration. As a bonus action, you can change the damage type, choosing from the options above. When you cast this spell using a spell slot of 3rd level or higher, you can maintain your concentration on the spell for up to 8 hours.");
    public static final Spell armorOfAgathys = new Spell("Armor of Agathys", 1, "", "1 action", 0, "v,s,m (cup of water)", "1 hour", "", "A protective magical force surrounds you, manifesting as a spectral frost that covers you and your gear. You gain 5 temporary hit points for the duration. If a creature hits you with a melee attack while you have these hit points, the creature takes 5 cold damage. At Higher Levels: When you cast this spell using a spell slot of 2nd level or higher, both the temporary hit points and the cold damage increase by 5 for each slot level above 1st.");
    public static final Spell armsOfHadar = new Spell("Arms of Hadar", 1, "", "1 action", 0, "v,s", "instant", "", "Tendrils of dark energy erupt from you and batter all creatures within 10 feet of you. Each creature in that area must make a Strength saving throw. On a failed save, a target takes 2d6 necrotic damage and can’t take reactions until its next turn. On a successful save, the creature takes half damage, but suffers no other effect. When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.");
    public static final Spell bane = new Spell("Bane", 1, "", "1 action", 30, "v,s,m (a drop of blood)", "1 min", "", "Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.");
    public static final Spell beastBond = new Spell("Beast Bond", 1, "", "1 action", 0, "v,s,m (a bit of fur wrapped in cloth)", "10 min", "", "You establish a telepathic link with one beast you touch that is friendly to you or charmed by you. The spell fails if the beast’s Intelligence is 4 or higher. Until the spell ends, the link is active while you and the beast are within line of sight of each other. Through the link, the beast can understand your telepathic messages to it, and it can telepathically communicate simple emotions and concepts back to you. While the link is active, the beast gains advantage on attack rolls against any creature within 5 feet of you that you can see.");
    public static final Spell bless = new Spell("Bless", 1, "", "1 action", 30, "v,s,m (a sprinkling of holy water)", "1 min", "", "You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.");
    public static final Spell burningHands = new Spell("Burning Hands", 1, "", "1 action", 15, "v,s", "instant", "", "As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one. The fire ignites any flammable objects in the area that aren't being worn or carried. When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.");
    public static final Spell catapult = new Spell("Catapult", 1, "", "1 action", 60, "s", "instant", "", "Choose one object weighing 1 to 5 pounds within range that isn’t being worn or carried. The object flies in a straight line up to 90 feet in a direction you choose before falling to the ground, stopping early if it impacts against a solid surface. If the object would strike a creature, that creature must make a Dexterity saving throw. On a failed save, the object strikes the target and stops moving. When the object strikes something, the object and what it strikes each take 3d8 bludgeoning damage. When you cast this spell using a spell slot of 2nd level or higher, the maximum weight of objects that you can target with this spell increases by 5 pounds, and the damage increases by 1d8, for each slot level above 1st.");
    public static final Spell causeFear = new Spell("Cause Fear", 1, "", "1 action", 60, "v", "concentration, up to 1 min", "", "You awaken the sense of mortality in one creature you can see within range. A construct or an undead is immune to this effect. The target must succeed on a Wisdom saving throw or become frightened of you until the spell ends. The frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above lst. The creatures must be within 30 feet of each other when you target them.");
    public static final Spell ceremony = new Spell("Ceremony", 1, "", "1 hour", 0, "v,s,m (25 gp of powedered silver, consumed)", "instant", "", "You perform a special religious ceremony that is infused with magic. When you cast the spell, choose one of the following rites, the target of which must be within 10 feet of you throughout the casting. 1. Atonement. You touch one willing creature whose alignment has changed, and you make a DC 20 Wisdom (Insight) check. On a successful check, you restore the target to its original alignment. 2, Bless Water. You touch one vial of water and cause it to become holy water. 3, Coming of Age. You touch one humanoid who is a young adult. For the next 24 hours, whenever the target makes an ability check, it can roll a d4 and add the number rolled to the ability check. A creature can benefit from this rite only once. Dedication. You touch one humanoid who wishes to be dedicated to your god’s service. For the next 24 hours, whenever the target makes a saving throw, it can roll a d4 and add the number rolled to the save. A creature can benefit from this rite only once. 4, Funeral Rite. You touch one corpse, and for the next 7 days, the target can’t become undead by any means short of a wish spell. 5, Wedding. You touch adult humanoids willing to be bonded together in marriage. For the next 7 days, each target gains a +2 bonus to AC while they are within 30 feet of each other. A creature can benefit from this rite again only if widowed.");
    public static final Spell chaosBolt = new Spell("Chaos Bolt", 1, "", "1 action", 120, "v,s", "instant", "", "You hurl an undulating, warbling mass of chaotic energy at one creature in range. Make a ranged spell attack against the target. On a hit, the target takes 2d8 + 1d6 damage. Choose one of the d8s. The number rolled on that die determines the attacks damage type, as shown below. 1, acid. 2, cold. 3, fire. 4, force. 5, lightning. 6, poison. 7, psychic. 8, thunder. If you roll the same number on both d8s, the chaotic energy leaps from the target to a different creature of your choice within 30 feet of it. Make a new attack roll against the new target, and make a new damage roll, which could cause the chaotic energy to leap again. A creature can be targeted only once by each casting of this spell. When you cast this spell using a spell slot of 2nd level or higher, each target takes 1d6 extra damage of the type rolled for each slot level above 1st.");
    public static final Spell charmPerson = new Spell("Charm Person", 1, "", "1 action", 30, "v,s", "1 hour", "", "You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.");
    public static final Spell chromaticOrb = new Spell("Chromatic Orb", 1, "", "1 action", 90, "v,s,m (50+gp diamond)", "instant", "", "You hurl a 4-inch-diameter sphere of energy at a creature that you can see within range. You choose acid, cold, fire, lightning, poison, or thunder for the type of orb you create, and then make a ranged spell attack against the target. If the attack hits, the creature takes 3d8 damage of the type you chose. When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.");
    public static final Spell colorSpray = new Spell("Color Spray", 1, "", "1 action", 15, "v,s,m (a pinch of powder or sand colored red, yellow, and blue)", "1 round", "", "A dazzling array of flashing, colored light springs from your hand. Roll 6d10; the total is how many hit points of creatures this spell can affect. Creatures in a 15-foot cone originating from you are affected in ascending order of their current hit points (ignoring unconscious creatures and creatures that can't see). Starting with the creature that has the lowest current hit points, each creature affected by this spell is blinded until the end of your next turn. Subtract each creature's hit points from the total before moving on to the creature with the next lowest hit points. A creature's hit points must be equal to or less than the remaining total for that creature to be affected. When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d10 for each slot level above 1st.");
    public static final Spell command = new Spell("Command", 1, "", "1 action", 60, "v", "1 round", "", "You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn. The spell has no effect if the target is undead, if it doesn't understand your language, or if your command is directly harmful to it. Some typical commands and their effects follow. You might issue a command other than one described here. If you do so, the GM determines how the target behaves. If the target can't follow your command, the spell ends. (approach, drop, flee, grovel, halt). When you cast this spell using a spell slot of 2nd level or higher, you can affect one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them.");
    public static final Spell compelledDuel = new Spell("Compelled Duel", 1, "", "1 bonus action", 30, "v", "concentration, up to 1 min", "", "One creature that you can see within range must make a Wisdom saving throw. On a failed save, the creature is drawn to you, compelled by your divine demand. For the duration, it has disadvantage on attack rolls against creatures other than you, and must make a Wisdom saving throw each time it attempts to move to a space that is more than 30 feet away from you; if it succeeds on this saving throw, this spell doesn’t restrict the target’s movement for that turn. The spell ends if you attack any other creature, if you cast a spell that targets a hostile creature other than the target, if a creature friendly to you damages the target or casts a harmful spell on it, or if you end your turn more than 30 feet away from the target.");
    //TODO: finish out level 1 spells and onward

    //Level 2
    //public static final Spell spell = new Spell("", 2, "", "1 action", 0, "", "", "", "");
    public static final Spell acidArrow = new Spell("Acid Arrow", 2, "", "1 action", 90, "v,s,m (powdered rhubard leaf & adders stomach)", "instant", "", "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 acid damage immediately and 2d4 acid damage at the end of its next turn. On a miss, the arrow splashes the target with acid for half as much of the initial damage and no damage at the end of its next turn. When you cast this spell using a spell slot of 3rd level or higher, the damage (both initial and later) increases by 1d4 for each slot level above 2nd.");
    public static final Spell aganazzarsScorcher = new Spell("Aganazzar’s Scorcher", 2, "", "1 action", 30, "v,s,m (red dragons scale)", "instant", "", "A line of roaring flame 30 feet long and 5 feet wide emanates from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 3d8 fire damage on a failed save, or half as much damage on a successful one. When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.");
    public static final Spell aid = new Spell("Aid", 2, "", "1 action", 30, "v,s,m (tiny strip of white cloth)", "8 hrs", "", "Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration. When you cast this spell using a spell slot of 3rd level or higher, a target's hit points increase by an additional 5 for each slot level above 2nd.");
    public static final Spell alterSelf = new Spell("Alter Self", 2, "", "1 action", 0, "v,s", "1 hr", "", "You assume a different form. When you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one. 1, Aquatic Adaptation. You adapt your body to an aquatic environment, sprouting gills and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed. 2, Change Appearance. You transform your appearance. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and distinguishing characteristics, if any. You can make yourself appear as a member of another race, though none of your statistics change. You also can't appear as a creature of a different size than you, and your basic shape stays the same; if you're bipedal, you can't use this spell to become quadrupedal, for instance. At any time for the duration of the spell, you can use your action to change your appearance in this way again. 3, Natural Weapons. You grow claws, fangs, spines, horns, or a different natural weapon of your choice. Your unarmed strikes deal 1d6 bludgeoning, piercing, or slashing damage, as appropriate to the natural weapon you chose, and you are proficient with your unarmed strikes. Finally, the natural weapon is magic and you have a +1 bonus to the attack and damage rolls you make using it.");
    public static final Spell animalMessenger = new Spell("Animal Messenger", 2, "", "1 action", 30, "v,s,m (morsel of food)", "24 hrs", "", "(Summary) You choose a tiny animal you can see and have it deliver a sort of 'audio recording' to a described person");
    public static final Spell arcaneLock = new Spell("Arcane Lock", 2, "", "1 action", 0, "v,s,m (25 gp of gold dust, consumed", "until dispelled", "", "Touch something which can be shut or locked and it becomes locked for the duration. Can designate others who can bypass the spell, and/or set a password that disables it when spoken when within 5 ft, for 1 min. Knock can supress the effect for 10 min. DC to break/force or lockpick the object increases by 10.");
    public static final Spell augury = new Spell("Augury", 2, "", "1 minute", 0, "v,s,m (specially marked sricks, bones, or other 25+gp tokens", "instant", "", "Using the material component as a divining tool you receive divine direction about specific course of action you'll take in the next 30 minutes. Can result in: Weall (good result), woe (bad result), weal & woe (mixed results), nothing (neither particularly good or bad). Doesn't account for changing circumstances. Repeated castings in 24 hrs gives cumulative 25% chance to give random result from dm.");
    public static final Spell barkskin = new Spell("Barkskin", 2, "", "1 action", 0, "v,s,m (handful of oak bark)", "concentration, 1 hr", "", "You touch a willing creature. Until the spell ends their skin appears bark-like and their AC can't become less than 16, regardless of armor.");
    public static final Spell beastSense = new Spell("Beast Sense", 2, "", "1 action", 0, "s", "concentration, 1 hr", "", "Touch a willing beast, you can see and hear through that beast until you use an action to return to your normal senses or the duration ends.");
    public static final Spell blindnessDeafness = new Spell("Blindness/Deafness", 2, "", "1 action", 30, "", "1 min", "", "You blind or deafen a foe within range, they make a CON saving throw each turn to negate or end the spell. When using a 3rd slot or higher you can target another creature for each slot above 2nd.");
    public static final Spell blur = new Spell("Blur", 2, "", "1 action", 0, "v", "concentration, 1 min", "", "You become blurry and any attack relying on sight gains disadvantage against you. Attacks not relying on sight of by attackers with truesight or the ability to see through illlusions are not affected.");
    public static final Spell brandingSmite = new Spell("Branding Smite", 2, "", "1 action", 0, "", "", "", "");

    //Level 3
    public static final Spell animateDead = new Spell("Animate Dead", 3, "", "1 min", 10, "v,s,m (drop of blood/piece of flesh/pinch of bone dust)", "instant", "", "This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or a zombie if you chose a corpse (the GM has the creature's game statistics). On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself against hostile creatures. Once given an order, the creature continues to follow it until its task is complete. The creature is under your control for 24 hours, after which it stops obeying any command you've given it. To maintain control of the creature for another 24 hours, you must cast this spell on the creature again before the current 24-hour period ends. This use of the spell reasserts your control over up to four creatures you have animated with this spell, rather than animating a new one. When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional undead creatures for each slot level above 3rd. Each of the creatures must come from a different corpse or pile of bones.");
    public static final Spell auraOfVitality = new Spell("Aura of Vitality", 3, "", "1 action", 30, "v", "concentration up to 1 min", "", "Healing energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. You can use a bonus action to cause one creature in the aura (including you) to regain 2d6 hit points.");
    public static final Spell beaconOfHope = new Spell("Beacon of Hope", 3, "", "1 action", 30, "v,s", "1 min", "", "This spell bestows hope and vitality. Choose any number of creatures within range. For the duration, each target has advantage on Wisdom saving throws and death saving throws, and regains the maximum number of hit points possible from any healing.");
    public static final Spell bestowCurse = new Spell("Bestow Curse", 3, "", "1 action", 0, "v,s", "1 min", "", "You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell. When you cast this spell, choose the nature of the curse from the following options: 1, Choose one ability score. While cursed, the target has disadvantage on ability checks and saving throws made with that ability score. 2, While cursed, the target has disadvantage on attack rolls against you. 3, While cursed, the target must make a Wisdom saving throw at the start of each of its turns. If it fails, it wastes its action that turn doing nothing. 4, While the target is cursed, your attacks and spells deal an extra 1d8 necrotic damage to the target. A remove curse spell ends this effect. At the DM's option, you may choose an alternative curse effect, but it should be no more powerful than those described above. The DM has final say on such a curse's effect. If you cast this spell using a spell slot of 4th level or higher, the duration is concentration, up to 10 minutes. If you use a spell slot of 5th level or higher, the duration is 8 hours. If you use a spell slot of 7th level or higher, the duration is 24 hours. If you use a 9th level spell slot, the spell lasts until it is dispelled. Using a spell slot of 5th level or higher grants a duration that doesn't require concentration.");

    //Level 4
    //public static final Spell spell = new Spell("", 4, "", "1 action", 0, "", "", "", "");
    public static final Spell arcaneEye = new Spell("Arcane Eye", 4, "", "1 action", 30, "v,s,m (bit of bat fur)", "1 hour", "", "You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet. The eye can look in every direction. As an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can't enter another plane of existence. A solid barrier blocks the eye's movement, but the eye can pass through an opening as small as 1 inch in diameter.");
    public static final Spell auraOfLife = new Spell("Aura of Life", 4, "", "1 action", 30, "v", "concentration up to 10 min", "", "Life-preserving energy radiates from you in an aura with a 30-foot radius. Until the spll ends, the aura moves with you, centered on you. Each nonhostile creature in the aura (including you) has resistance to necrotic damage, and its hit point maximum can’t be reduced. In addition, a nonhostile, living creature regains 1 hit point when it starts its turn in the arua with 0 hit points.");
    public static final Spell auraOfPurity = new Spell("Aura of Purity", 4, "", "1 action", 30, "v", "concentration up to 10 min", "", "Purifying energy radiates from you in an aura with a 30-foot radius. Until the spell ends, the aura moves with you, centered on you. Each nonhostile creature in the aura (including you) can’t become diseased, has resistance to poison damage, and has advantage on saving throws against effects that cause any of the following conditions: blinded, charmed, deafended, frightened, paralyzed, poisoned, and stunned.");
    public static final Spell banishment = new Spell("Banishment", 4, "", "1 action", 60, "v,s,m (item distasteful to the target)", "up to 1 min", "", "You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to the plane of existence you're on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. If the target is native to a different plane of existence than the one you're on, the target is banished with a faint popping noise, returning to its home plane. If the spell ends before 1 minute has passed, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied. Otherwise, the target doesn't return. When you cast this spell using a spell slot of 5th level or higher, you can target one additional creature for each slot level above 4th.");

    //Level 5
    //public static final Spell spell = new Spell("", 5, "", "1 action", 0, "", "", "", "");
    public static final Spell animateObjects = new Spell("Animate Objects", 5, "", "1 action", 120, "v,s", "1 min", "", "See https://www.dndbeyond.com/spells?page=16&sort=level");
    public static final Spell antilifeShell = new Spell("Antilife Shell", 5, "", "1 action", 10, "v,s", "1 hr", "", "A shimmering barrier extends out from you in a 10-foot radius and moves with you, remaining centered on you and hedging out creatures other than undead and constructs. The barrier lasts for the duration. The barrier prevents an affected creature from passing or reaching through. An affected creature can cast spells or make attacks with ranged or reach weapons through the barrier. If you move so that an affected creature is forced to pass through the barrier, the spell ends.");
    public static final Spell arcaneHane = new Spell("Arcane Hand", 5, "", "1 action", 120, "v,s,m (eggshell and snakeskin glove)", "1 min", "", "See https://www.dndbeyond.com/spells?page=16&sort=level");
    public static final Spell awaken = new Spell("Awaken", 5, "", "8 hrs", 0, "v,s,m (1,000gp+ agate, consumed)", "instant", "", "After spending the casting time tracing magical pathways within a precious gemstone, you touch a Huge or smaller beast or plant. The target must have either no Intelligence score or an Intelligence of 3 or less. The target gains an Intelligence of 10. The target also gains the ability to speak one language you know. If the target is a plant, it gains the ability to move its limbs, roots, vines, creepers, and so forth, and it gains senses similar to a human's. Your GM chooses statistics appropriate for the awakened plant, such as the statistics for the awakened shrub or the awakened tree. The awakened beast or plant is charmed by you for 30 days or until you or your companions do anything harmful to it. When the charmed condition ends, the awakened creature chooses whether to remain friendly to you, based on how you treated it while it was charmed.");

    //Level 6
    //public static final Spell spell = new Spell("", 6, "", "1 action", 0, "", "", "", "");
    //public static final Spell arcaneGate = new Spell("Arcane Gate", 6, "", "1 action", 0, "", "", "", "");
    public static final Spell bladeBarrier = new Spell("Blade Barrier", 6, "", "1 action", 90, "v,s", "10 min", "", "You create a vertical wall of whirling, razor-sharp blades made of magical energy. The wall appears within range and lasts for the duration. You can make a straight wall up to 100 feet long, 20 feet high, and 5 feet thick, or a ringed wall up to 60 feet in diameter, 20 feet high, and 5 feet thick. The wall provides three-quarters cover to creatures behind it, and its space is difficult terrain. When a creature enters the wall's area for the first time on a turn or starts its turn there, the creature must make a Dexterity saving throw. On a failed save, the creature takes 6d10 slashing damage. On a successful save, the creature takes half as much damage.");
    public static final Spell bonesOfTheEarth = new Spell("Bones of the Earth", 6, "", "1 action", 120, "v,s", "instant", "", "You cause up to six pillars of stone to burst from places on the ground that you can see within range. Each pillar is a cylinder that has a diameter of 5 feet and a height of up to 30 feet. The ground where a pillar appears must be wide enough for its diameter, and you can target the ground under a creature if that creature is Medium or smaller. Each pillar has AC 5 and 30 hit points. When reduced to 0 hit points, a pillar crumbles into rubble, which creates an area of difficult terrain with a 10-foot radius that lasts until the rubble is cleared. Each 5-foot-diameter portion of the area requires at least 1 minute to clear by hand. If a pillar is created under a creature, that creature must succeed on a Dexterity saving throw or be lifted by the pillar. A creature can choose to fail the save. If a pillar is prevented from reaching its full height because of a ceiling or other obstacle, a creature on the pillar takes 6d6 bludgeoning damage and is restrained, pinched between the pillar and the obstacle. The restrained creature can use an action to make a Strength or Dexterity check (the creature’s choice) against the spell’s save DC. On a success, the creature is no longer restrained and must either move off the pillar or fall off it. When you cast this spell using a spell slot of 7th level or higher, you can create two additional pillars for each slot level above 6th.");
    public static final Spell chainLightning = new Spell("Chain Lightning", 6, "", "1 action", 150, "v,s,m (bit of fur, piece of amber/glass/crystal-rod, and 3 silver pins", "instant", "", "You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts. A target must make a Dexterity saving throw. The target takes 10d8 lightning damage on a failed save, or half as much damage on a successful one. When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.");

    //Level 7
    //public static final Spell spell = new Spell("", 7, "", "1 action", 0, "", "", "", "");
    public static final Spell conjureCelestial = new Spell("Conjure Celestial", 7, "", "1 min", 90, "v,s", "1 hr", "", "You summon a celestial of challenge rating 4 or lower, which appears in an unoccupied space that you can see within range. The celestial disappears when it drops to 0 hit points or when the spell ends. The celestial is friendly to you and your companions for the duration. Roll initiative for the celestial, which has its own turns. It obeys any verbal commands that you issue to it (no action required by you), as long as they don't violate its alignment. If you don't issue any commands to the celestial, it defends itself from hostile creatures but otherwise takes no actions. The GM has the celestial's statistics. (Sample: Pegasus). When you cast this spell using a 9th-level spell slot, you summon a celestial of challenge rating 5 or lower.");
    //public static final Spell crownOfStars = new Spell("Crown of Stars", 7, "", "1 action", 0, "", "", "", "");
    public static final Spell delayedBlastFireball = new Spell("Delayed Blast Fireball", 7, "", "1 action", 150, "v,s,m (tiny ball of bat guano and sulfur", "1 min", "", "A beam of yellow light flashes from your pointing finger, then condenses to linger at a chosen point within range as a glowing bead for the duration. When the spell ends, either because your concentration is broken or because you decide to end it, the bead blossoms with a low roar into an explosion of flame that spreads around corners. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A creature takes fire damage equal to the total accumulated damage on a failed save, or half as much damage on a successful one. The spell's base damage is 12d6. If at the end of your turn the bead has not yet detonated, the damage increases by 1d6. f the glowing bead is touched before the interval has expired, the creature touching it must make a Dexterity saving throw. On a failed save, the spell ends immediately, causing the bead to erupt in flame. On a successful save, the creature can throw the bead up to 40 feet. When it strikes a creature or a solid object, the spell ends, and the bead explodes. The fire damages objects in the area and ignites flammable objects that aren't being worn or carried. When you cast this spell using a spell slot of 8th level or higher, the base damage increases by 1d6 for each slot level above 7th.");

    //Level 8
    //public static final Spell spell = new Spell("", 8, "", "1 action", 0, "", "", "", "");
    public static final Spell abiDalzimsHorridWilting = new Spell("Abi-Dalzim's Horrid Wilting", 8, "", "1 action", 150, "v,s,m (bit of sponge)", "instant", "", "You draw the moisture from every creature in a 30-foot cube centered on a point you choose within range. Each creature in that area must make a Constitution saving throw. Constructs and undead aren’t affected, and plants and water elementals make this saving throw with disadvantage. A creature takes 12d8 necrotic damage on a failed save, or half as much damage on a successful one. Nonmagical plants in the area that aren’t creatures, such as trees and shrubs, wither and die instantly.");
    public static final Spell animalShapes = new Spell("Animal Shapes", 8, "", "1 action", 30, "v,s", "24 hrs", "", "Your magic turns others into beasts. Choose any number of willing creatures that you can see within range. You transform each target into the form of a Large or smaller beast with a challenge rating of 4 or lower. On subsequent turns, you can use your action to transform affected creatures into new forms. The transformation lasts for the duration for each target, or until the target drops to 0 hit points or dies. You can choose a different form for each target. A target's game statistics are replaced by the statistics of the chosen beast, though the target retains its alignment and Intelligence, Wisdom, and Charisma scores. The target assumes the hit points of its new form, and when it reverts to its normal form, it returns to the number of hit points it had before it transformed. If it reverts as a result of dropping to 0 hit points, any excess damage carries over to its normal form. As long as the excess damage doesn't reduce the creature's normal form to 0 hit points, it isn't knocked unconscious. The creature is limited in the actions it can perform by the nature of its new form, and it can't speak or cast spells. The target's gear melds into the new form. The target can't activate, wield, or otherwise benefit from any of its equipment.");

    //Level 9
    //public static final Spell spell = new Spell("", 9, "", "1 action", 0, "", "", "", "");
    public static final Spell astralProjection = new Spell("Astral Projection", 9, "", "1 hr", 10, "v,s,m ({1 1,000gp jacinth & 100+gp silver bar} per target)", "special", "", "See https://www.dndbeyond.com/spells?page=24&sort=level");
    public static final Spell foresight = new Spell("Foresight", 9, "", "1 min", 0, "v,s,m (hummingbird feather)", "8 hrs", "", "You touch a willing creature and bestow a limited ability to see into the immediate future. For the duration, the target can't be surprised and has advantage on attack rolls, ability checks, and saving throws. Additionally, other creatures have disadvantage on attack rolls against the target for the duration. This spell immediately ends if you cast it again before its duration ends.");


    public static final List<Spell> masterSpellList = new ArrayList<Spell>(Arrays.asList(
            acidSplash,
            bladeWard,
            boomingBlade,
            chillTouch,
            controlFlames,
            createBonfire,
            dancingLights,
            druidcraft,
            eldritchBlast,
            encodeThoughts,
            fireBolt,
            friends,
            frostbite,
            greenFlameBlade,
            guidance,
            gust,
            infestation,
            light,
            lightningLure,
            mageHand,
            magicStone,
            mending,
            message,
            mindSliver,
            minorIllusion,
            moldEarth,
            poisonSpray,
            prestidigitation,
            primalSavagery,
            produceFlame,
            rayOfFrost,
            resistance,
            sacredFlame,
            shapeWater,
            shillelagh,
            shockingGrasp,
            spareTheDying,
            thaumaturgy,
            thornWhip,
            thunderclap,
            tollTheDead,
            trueStrike,
            viciousMockery,
            wordOfRadiance,

            alarm,
            absorbElements,
            animalFriendship,
            arcaneWeapon,
            armorOfAgathys,
            armsOfHadar,
            bane,
            beastBond,
            bless,
            burningHands,
            catapult,
            causeFear,
            ceremony,
            chaosBolt,
            charmPerson,
            chromaticOrb,
            colorSpray,
            command,
            compelledDuel,
            animalMessenger,
            arcaneLock,
            augury,
            barkskin,
            beastSense,
            blindnessDeafness,
            blur,
            brandingSmite,

            acidArrow,
            aganazzarsScorcher,
            aid,
            alterSelf,

            animateDead,
            auraOfVitality,
            beaconOfHope,
            bestowCurse,

            arcaneEye,
            auraOfLife,
            auraOfPurity,
            banishment,

            animateObjects,
            antilifeShell,
            arcaneHane,
            awaken,

            bladeBarrier,
            bonesOfTheEarth,
            chainLightning,

            conjureCelestial,
            delayedBlastFireball,

            abiDalzimsHorridWilting,
            animalShapes,

            astralProjection,
            foresight
    ));

    public static List<Spell> getSpellListByLevel(int level) {
        List<Spell> listToReturn = new ArrayList<Spell>(Arrays.asList());
        for (Spell temp : masterSpellList) {
            if (temp.level == level) {
                listToReturn.add(temp);
            }
        }
        return listToReturn;
    }
}
